#
# Copyright (C) 2025 Bitsea GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https:www.apache.orglicensesLICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
# License-Filename: LICENSE
#

# spring.profiles.active=local

# SERVER CONFIGURATION
server.port=${SERVER_PORT:8090}
server.servlet.context-path=/boc

# NATS JETSTREAM BASE CONFIGURATION
nats.stream_name=${NATS_STREAM_NAME:occtet}
nats.stream_subjects_config=work.>
nats.send_subject_ort_run=work.ortRunStarter
nats.send_subject_spdx=work.spdx
nats.send-subject-cyclonedx=work.cyclonedx
nats.send_subject_export=work.export
nats.send-subject-cyclonedx-export=work.cyclonedxExport
nats.send_subject_foss=work.fossreport
nats.send_subject_vulnerabilities=work.vulnerabilities
nats.send_subject_ort_result=work.ortProcessRun
nats.send_subject_download=work.download

# Time to Live (long/h)
nats.object-store-ttl=${NATS_OBJECT_STORE_TTL:168}

# SCHEDULED TASKS
processRun.cron=${PROCESS_RUN_CRON:0 */2 * * * *}
#2 min

# JMIX & VAADIN CONFIGURATION
jmix.core.user-class=eu.occtet.bocfrontend.entity.User
jmix.ui.login-view-id=LoginView
jmix.ui.main-view-id=MainView
jmix.ui.menu-config=/eu/occtet/bocfrontend/menu.xml
jmix.ui.composite-menu=false
jmix.ui.default-view-id=CuratorTask.list
jmix.core.fetch-plans-config=/eu/occtet/bocfrontend/fetch-plans.xml

ui.login.defaultUsername=${DEFAULT_ADMIN_USERNAME:admin}
ui.login.defaultPassword=${DEFAULT_ADMIN_PASSWORD:admin}

jmix.core.available-locales=en,de,fr,it,es

vaadin.launch-browser=false

# Max file size
spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE:40MB}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE:40MB}

# DATABASE / LIQUIBASE BASE
main.liquibase.change-log=eu/occtet/bocfrontend/liquibase/changelog.xml
spring.jpa.hibernate.ddl-auto=none

# LOGGING
logging.level.org.atmosphere=warn
logging.level.eclipselink.logging.sql=info
logging.level.io.jmix.core.datastore=info
logging.level.org.springframework.security=info
logging.level.io.jmix.core.AccessLogger=info

logging.level.io.jmix=info
logging.level.eu.occtet.bocfrontend=info

spring.jpa.properties.eclipselink.ddl-generation=create-or-extend-tables
spring.jpa.properties.eclipselink.ddl-generation.output-mode=database
eclipselink.ddl-generation = create-or-extend-tables
eclipselink.ddl-generation.output-mode = database

jmix.eclipselink.shared-cache.enabled=false


